# Travis CI setup

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/requirements_dev.txt
  - python setup.py install

  - export HYPOTHESIS_PROFILE="ci"

script:
  - pytest --cov=. --cov-report term-missing --durations 5 -W error

after_success:
  - coveralls -i
